#! /bin/sh
# <repo>/.travis/travis-key
# Install Travis gem:
#   apt-get install gcc libffi-dev ruby ruby-dev
#   gem install travis --no-rdoc --no-ri
#   travis login --org

[ $# -gt 0 ] || {
  echo "Usage: $0 <repo>"
  return 1
}

repo=$1

# defaults
key=""

# config can override defaults
CONF=$HOME/.travis-key.conf
[ -r "$CONF" ] && . "$CONF"

travis sync --org
travis enable --org -r "$repo"
travis env set gpg_key "$key" -p
