#! /bin/sh
# <repo>/.travis/travis-key
# Install Travis gem:
#   apt-get install gcc libffi-dev ruby ruby-dev
#   gem install travis --no-rdoc --no-ri
#   travis login --org

# Usage: $0 -r user/repo [<travis opts>]

# defaults
gpg_key=""

# config can override defaults
CONF=$HOME/.travis-key.conf
[ -r "$CONF" ] && . "$CONF"

travis sync --org
travis enable --org $@
travis env set gpg_key "$gpg_key" -p $@
