#! /bin/sh
# cd <repo>; ./travis-key
# Install Travis gem:
#   apt-get install gcc libffi-dev ruby ruby-dev
#   gem install travis --no-rdoc --no-ri
#   travis login

# Usage: $0 [-r user/repo] [<other travis opts>]
# If repo is not specified, travis defaults to repo from current dir
# To force 'travis-ci.com' endpoint, use '--com'

# defaults
opts="--com"
github_key=""

# config can override defaults
CONF=$HOME/.travis-key.conf
[ -r "$CONF" ] && . "$CONF"

travis sync $opts
travis enable $opts $@
travis env set github_key "$github_key" -p $opts $@
